name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 0.1.0
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/form_builder_file_picker

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^3.8.1
  file_picker: ^1.5.0+2
  permission_handler: ^4.4.0+hotfix.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
