name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 1.2.0-nullsafety.0
homepage: https://github.com/danvick/form_builder_file_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  community_material_icon: ^5.9.55
  file_picker: ^4.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^6.0.1
  permission_handler: ^8.2.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
